#regular: (https?|http|ftp|file):\/\/[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]|(href|src)="[\'\"]?([^\'\"]*)[^\'\"]
regular: (https?|http|ftp|file):\/\/[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]|(?<=href=|src=)/.+?(?= |>)|(?<=href=|src=).+?(?= |>)

headers:
  content-type: application/json
  user-agent: Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)
#domain: (https?://.*)+?(?=/|/[a-zA-Z])

#subdomain: (?<=https?://)[^/].+?(?=/|"|') #域名
subdomain: (?<=//)[\w\.]+[^:/|?]
domain: (https?://)[^/].+?(?=/|"|') #带http的域名
threadnumber: 20


